const APP_URL = process.env.EXPO_PUBLIC_sBASE_URL;
const APP_ANON_KEY = process.env.EXPO_PUBLIC_sBASE_ANON_KEY;
const APP_WSS_URL = process.env.EXPO_PUBLIC_sBASE_WSS;
const ISW_PROD_CLIENT_SECRET = process.env.EXPO_PUBLIC_ISW_PROD_CLIENT_SECRET;
const ISW_PROD_CLIENT_ID = process.env.EXPO_PUBLIC_ISW_PROD_CLIENT_ID;
const BVNKEY = process.env.EXPO_PUBLIC_BVN_KEY;
const ISW_PROD_URL = process.env.EXPO_PUBLIC_ISW_PROD_URL;
const ISW_TERMINAL_ID = process.env.EXPO_PUBLIC_ISW_PROD_TERMINAL_ID;
const ISW_GENERATE_TOKEN_URL = process.env.EXPO_PUBLIC_ISW_PROD_GENERATE_TOKEN_URL;
const ISW_REF_PREFIX = process.env.EXPO_PUBLIC_ISW_REF_PREFIX;
const ISW_VA_CLIENT_ID = process.env.EXPO_PUBLIC_ISW_VA_CLIENT_ID;
const ISW_VA_CLIENT_SECRET = process.env.EXPO_PUBLIC_ISW_VA_CLIENT_SECRET;
const ISW_VA_ENDPOINT = process.env.EXPO_PUBLIC_ISW_VA_ENDPOINT;
const ISW_VA_MERCHANT_ID = process.env.EXPO_PUBLIC_ISW_VA_MERCHANT_ID;


export {
    APP_URL,
    APP_ANON_KEY,
    APP_WSS_URL,
    ISW_PROD_CLIENT_SECRET,
    ISW_PROD_CLIENT_ID,
    BVNKEY,
    ISW_PROD_URL,
    ISW_TERMINAL_ID,
    ISW_GENERATE_TOKEN_URL,
    ISW_REF_PREFIX,
    ISW_VA_CLIENT_ID,
    ISW_VA_CLIENT_SECRET,
    ISW_VA_ENDPOINT,
    ISW_VA_MERCHANT_ID
}